version: 2.1

jobs:
  linux-python37:    # This is first job --- pytest task with Python 3.7.
    docker:
      - image: circleci/python:3.7
#         auth:
#           username: chisanan232
#           password: $DOCKERHUB_PASSWORD
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout    # this pulls code down from GitHub
      - run:
         name: Test MySQL connection
         command: mysql -u root -h 127.0.0.1 -ppassword
      - run:
         name: Check Python Version
         command: python --version
      - run:
         name: Upgrade and install Python dependencies
         command: |
             pip install -U pip
             pip install -U pytest
             pip install -U pytest-cov
             pip install codecov
             pip install pytest-rerunfailures
             pip install requests
             pip install beautifulsoup4
             pip install -r dev-requirements.txt
      - run:
         name: Run PyTest command to test
         command: |
             pytest
      - run:
         name: Submit calculation result of testing coverage of project code to codecov
#         command: |
#             coveralls    # submit coverage to coveralls
         command: |
             codecov -t $CODECOV_TOKEN    # submit coverage to codecov

# Under the workflows: map, we can coordinate above jobs, defined above.
workflows:
  version: 2.1
  build_and_test:    # this is the name of our workflow
    jobs:    # and here we list the jobs we are going to run.
      - linux-python37

