name: smoothcrawler testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pip
          pip install -U pytest
          pip install -U pytest-cov
          pip install codecov
          pip install pytest-rerunfailures
          pip install requests
          pip install beautifulsoup4
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest

      - name: Get secret token from base64
        env:
          KEYSTORE_BASE64: ${{ secrets.CODECOV_TOKEN }}
        run: |
          echo import certificate from secrets and regenerate the file
          echo $KEYSTORE_BASE64 | base64 -d > ./codecov.token

      - name: Submit calculation result of testing coverage of project code to codecov
        run: codecov -f ./codecov.token    # submit coverage to codecov

